name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-checks-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> "$GITHUB_PATH"

      - name: Show versions
        run: |
          pixi --version
          pixi info
	  
      - name: Install dependencies and package
        run: pixi install .

      - name: Run style checks (pep8)
        run: pixi run check

      - name: Run unit tests
        run: pixi run test
